---
apiVersion: v1
kind: Secret
metadata:
  name: objstore
stringData:
  objstore.yml: |-
    type: S3
    config:
      bucket: prometheus-metrics
      endpoint: "dev-ovng-poc2-lead.ovng.dev.myovcloud.com:30325"
      insecure: true
      access_key: "l3WSXJNdiD5dAbRd"
      secret_key: "cT3pXutqcYlq49Xlf1TQkc0Ibsvw16xi"
