global:
  scrape_interval: 15s # How frequently to scrape targets
  evaluation_interval: 15s
  #  external_labels:
  #    cluster: demo-cluster-2
  #remote_write:
  #  - url: http://vpnb.sqa-eu.ovng.myovcloud.com:32709/api/v1/push

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['poc-m2.ovng.dev.myovcloud.com:9100'] # Node Exporter address (replace as needed)

rule_files:
  - "rules/myrules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['poc-lead.ovng.dev.myovcloud.com:9093'] # Alertmanager address
