global:
  scrape_interval: 15s # How frequently to scrape targets
  evaluation_interval: 15s
  external_labels:
    cluster: poc-docker
    #remote_write:
    #  - url: http://vpnb.sqa-eu.ovng.myovcloud.com:32709/api/v1/push

scrape_configs:
  - job_name: 'example_service'
    static_configs:
      - targets: ['localhost:9090'] # Replace with your target's address

  - job_name: 'node_exporter'
    file_sd_configs:
      - files:
        - file_sd.yml
  
  - job_name: 'python_exporter'
    static_configs:
      - targets: ['poc-lead.ovng.dev.myovcloud.com:8001'] 
  
  - job_name: 'openvpn-metrics'
    static_configs:
      - targets: ['vpn.sqa-eu.ovng.myovcloud.com:9177'] 
  
  - job_name: 'haproxy'
    static_configs:
      - targets: ['poc-lb.ovng.dev.myovcloud.com:9101'] 
  
  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['poc-lead.ovng.dev.myovcloud.com:9115'] 
  
  - job_name: 'pushgateway'
    honor_labels: true # for source of metric overwrite the label of pushgateway
    static_configs:
      - targets: ['poc-lead.ovng.dev.myovcloud.com:9092'] 
  
  - job_name: 'prometheus-website'
    static_configs:
      - targets:
        - prometheus.io
    metrics_path: /probe
    params:
      module:
        - http_2xx
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
        # <=> pram.target of dest = address of source (promethues.io)
      - source_labels: [__param_target]
        target_label: instance
        # <=> instance of dest = pram.target of source (
      - target_label: __address__
        replacement: poc-lead.ovng.dev.myovcloud.com:9115 
        # <=> address of dest (origin is prometheus.io) is replace to poc-lead ...
        
  - job_name: 'ec2'
    ec2_sd_configs:
      - access_key: 
        secret_key: 
        region: ap-southeast-1
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip]
        replacement: "${1}:9100"
        target_label: __address__

  - job_name: 'example-job'
    static_configs:
      - targets:
        - 'target1:9090'
        - 'target2:9090'
    relabel_configs:
      - source_labels: [__address__, __metrics_path__]
        separator: "@"
        target_label: label1 # = target1:9090@/metrics
      
      - source_labels: [__address__, __metrics_path__]
        separator: "@"
        regex: "target1:9090@(.*)"
        target_label: label2 # = /metrics
        
      - source_labels: [__address__, __metrics_path__]
        target_label: instance
        replacement: 'new_instance_$2'
      - target_label: job
        replacement: 'example-job2'

rule_files:
  - "rules/myrules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['poc-lead.ovng.dev.myovcloud.com:9093'] # Alertmanager address
