---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: storegateway
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 32324
    - port: 10901
      targetPort: grpc
      protocol: TCP
      name: grpc
      nodePort: 32325
  selector:
    app.kubernetes.io/name: storegateway
