global:
  scrape_interval: 5s
  external_labels:
    cluster: eu1
    replica: 0
    tenant: team-eu # Not needed, but a good practice if you want to grow this to multi-tenant system some day.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:8080']
  - job_name: 'sidecar'
    static_configs:
      - targets: ['127.0.0.1:18080']
  - job_name: 'minio'
    metrics_path: /minio/prometheus/metrics
    static_configs:
      - targets: ['127.0.0.1:8000']
  - job_name: 'querier'
    static_configs:
      - targets: ['127.0.0.1:8081']
  - job_name: 'store_gateway'
    static_configs:
      - targets: ['127.0.0.1:18081']
